# Generated by Django 6.1 on 2026-08-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.TextField(blank=True),
        ),
    ]
